CREATE TABLE `raw_merchant_items` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `spawn_id` int(10) unsigned NOT NULL default '0',
  `item_id` int(10) unsigned NOT NULL,
  `item_name` varchar(128) NOT NULL default ' ',
  `unknown` tinyint(3) unsigned NOT NULL default '0',
  `price` int(10) unsigned NOT NULL default '0',
  `unknown2` int(10) unsigned NOT NULL default '0',
  `stack_size` smallint(5) unsigned NOT NULL default '0',
  `icon` smallint(5) unsigned NOT NULL default '0',
  `unknown3` tinyint(3) unsigned NOT NULL default '0',
  `level` tinyint(3) unsigned NOT NULL default '0',
  `unknown4` tinyint(3) unsigned NOT NULL default '0',
  `unknown5` smallint(5) unsigned NOT NULL default '0',
  `tier` tinyint(3) unsigned NOT NULL default '0',
  `unknown6` int(10) unsigned NOT NULL default '0',
  `item_id2` int(10) unsigned NOT NULL default '0',
  `stack_size2` smallint(5) unsigned NOT NULL default '0',
  `description` varchar(512) NOT NULL default ' ',
  `log_file` varchar(128) NOT NULL default ' ',
  `language_type` tinyint(3) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `SpawnItemNDX` (`item_id`,`spawn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;