ALTER TABLE `raw_spawn_info` 
  CHANGE `level` `min_level` TINYINT (3) UNSIGNED DEFAULT '0' NOT NULL,
  ADD COLUMN `max_level` TINYINT (3) UNSIGNED DEFAULT '0' NOT NULL AFTER `min_level`,
  ADD COLUMN `min_size` SMALLINT (5) UNSIGNED DEFAULT '0' NOT NULL AFTER `pos_size`,
  ADD COLUMN `max_size` SMALLINT (5) UNSIGNED DEFAULT '0' NOT NULL AFTER `min_size`,
  ADD COLUMN `randomize` INT (10) UNSIGNED DEFAULT '0' NOT NULL AFTER `title`;
