DROP TABLE IF EXISTS `raw_factions`;
CREATE TABLE `raw_factions` (
  `faction_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) DEFAULT NULL,
  `category` VARCHAR(512) DEFAULT NULL,
  `description` VARCHAR(512) DEFAULT NULL,
  `unknown` VARCHAR(512) DEFAULT NULL,
  `con` TINYINT(3) NOT NULL DEFAULT '0',
  `percentage` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `unknown2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `value` MEDIUMINT(5) NOT NULL DEFAULT '0',
  `log_file` VARCHAR(255) DEFAULT '',
  `data_version` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`faction_id`)
) ENGINE=MYISAM DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
