DROP TABLE IF EXISTS `raw_spell_visuals`;

CREATE TABLE `raw_spell_visuals` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `spell_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `num_targets` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spell_visual1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spell_visual2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `cast_time` FLOAT NOT NULL DEFAULT '0',
  `spell_level` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spell_tier` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `data_version` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `log_file` VARCHAR(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MYISAM;
