CREATE TABLE `raw_poi_locations`( 
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT , 
	`unknown` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' , 
	`x` FLOAT NOT NULL DEFAULT '0' , 
	`y` FLOAT NOT NULL DEFAULT '0' , 
	`z` FLOAT NOT NULL DEFAULT '0' , 
	`num_locations` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' , 
	`data_version` INT(10) UNSIGNED NOT NULL DEFAULT '0' , 
	`log_file` VARCHAR(250) NOT NULL DEFAULT '' , 
	PRIMARY KEY (`id`)
) ENGINE=MyISAM;
