DROP TABLE IF EXISTS `raw_spells_aa`;
CREATE TABLE `raw_spells_aa` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, 
	`aa_spell_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`spell_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`tier` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`unknown` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`icon` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`icon2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`current_rank` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`max_rank` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`rank_cost` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`unknown2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`language_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`log_file` VARCHAR(255) DEFAULT '',
	PRIMARY KEY (`id`),
	UNIQUE KEY `NewIndex1` (`aa_spell_id`,`language_type`)
) ENGINE=MYISAM CHECKSUM=1 AUTO_INCREMENT=1 COMMENT='' DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC CHARSET=latin1 COLLATE=latin1_swedish_ci;